# Created using wingetcreate

PackageIdentifier: Digiarty,Inc.WinXDVDRipperPlatnum
PackageVersion: 8.20.6
Installers:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://www.winxdvd.com/download/winx-dvd-ripper-pt.exe
  InstallerSha256: EEF004FDEB4856681DDEDDE2B103979E3EEB71692C7308319395EA5461D3D755
ManifestType: installer
ManifestVersion: 1.0.0
