# Created using wingetcreate

PackageIdentifier: AudibleInc.AudibleSync
PackageVersion: 1.8.8
PackageLocale: en-US
Publisher: Audible Inc
PackageName: AudibleSync
License: Copyright © 2021 Audible Inc
ShortDescription: AudibleSync
ManifestType: defaultLocale
ManifestVersion: 1.0.0
